apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ template "agentEnv.fullname" $ -}}-sandbox-egress
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
  labels:
    {{- toYaml $.Values.labels | nindent 4 }}
spec:
  description: |
    Allow egress to:
    - cluster-wide DNS (kube-dns) for certain domains,
    - all Pods in the same agent sandbox,
    - any configured allowDomains, allowEntities, or allowCIDR.
    To prevent DNS exfiltration, only allow DNS lookups for:
    - services in this namespace,
    - allowDomains, or
    - allowEntities.
  endpointSelector:
    matchLabels:
      io.kubernetes.pod.namespace: {{ .Release.Namespace }}
      {{- include "agentEnv.selectorLabels" $ | nindent 6 }}
  egress:
    - toEndpoints:
      - matchLabels:
          io.kubernetes.pod.namespace: kube-system
          k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*.{{ .Release.Namespace }}.svc.cluster.local"
              {{- range .Values.allowDomains }}
              - matchPattern: "{{ . }}"
              {{- end }}
              {{- if or (has "all" .Values.allowEntities) (has "world" .Values.allowEntities) }}
              - matchPattern: "*"
              {{- end }}
    - toEndpoints:
      - matchLabels:
          io.kubernetes.pod.namespace: {{ .Release.Namespace }}
          {{- include "agentEnv.selectorLabels" $ | nindent 10 }}
    {{- if .Values.allowDomains }}
    - toFQDNs:
    {{- range .Values.allowDomains }}
      - matchPattern: "{{ . }}"
    {{- end }}
    {{- end }}
    {{- with .Values.allowEntities }}
    - toEntities:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.allowCIDR }}
    - toCIDR:
      {{- toYaml . | nindent 6 }}
    {{- end }}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ template "agentEnv.fullname" $ -}}-sandbox-default-deny-ingress
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
  labels:
    {{- toYaml $.Values.labels | nindent 4 }}
spec:
  description: Default deny ingress. Allow other policies to be more specific.
  endpointSelector:
    matchLabels:
      io.kubernetes.pod.namespace: {{ .Release.Namespace }}
      {{- include "agentEnv.selectorLabels" $ | nindent 6 }}
  ingress:
    - {}
{{- if .Values.networks }}
  {{- range $svcName, $svc := .Values.services }}
    {{- if $svc.networks }}
      {{- range $net := $svc.networks }}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ template "agentEnv.fullname" $ }}-svc-{{ $svcName }}-{{ $net }}-ingress
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
  labels:
    {{- toYaml $.Values.labels | nindent 4 }}
spec:
  description: |
    Allow ingress to workload "{{ $svcName }}" from same sandbox on network "{{ $net }}".
    If ports are specified, only those ports are exposed; otherwise all ports are allowed.
  endpointSelector:
    matchLabels:
      io.kubernetes.pod.namespace: {{ $.Release.Namespace }}
      {{- include "agentEnv.selectorLabels" $ | nindent 6 }}
      inspect/service: {{ $svcName }}
      aisi.gov.uk/network-{{ $net }}: "true"
  ingress:
    - fromEndpoints:
      - matchLabels:
          io.kubernetes.pod.namespace: {{ $.Release.Namespace }}
          {{- include "agentEnv.selectorLabels" $ | nindent 10 }}
          aisi.gov.uk/network-{{ $net }}: "true"
      {{- if $svc.ports }}
      toPorts:
        - ports:
{{ include "agentEnv.servicePortsListFor" (dict "svc" $svc) | nindent 12 }}
      {{- end }}
      {{- end }}
    {{- else }}
    {{- /* If no network fallback to default rule (no ingress) */}}
    {{- end }}
  {{- end }}
{{- else }}
  {{- /* No global networks: allow same-sandbox ingress per service (no network scoping) */}}
  {{- range $svcName, $svc := .Values.services }}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ template "agentEnv.fullname" $ }}-svc-{{ $svcName }}-ingress
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
  labels:
    {{- toYaml $.Values.labels | nindent 4 }}
spec:
  description: |
    Allow ingress to workload "{{ $svcName }}" from same sandbox.
    If ports are specified, only those ports are exposed; otherwise all ports are allowed.
  endpointSelector:
    matchLabels:
      io.kubernetes.pod.namespace: {{ $.Release.Namespace }}
      {{- include "agentEnv.selectorLabels" $ | nindent 6 }}
      inspect/service: {{ $svcName }}
  ingress:
    - fromEndpoints:
      - matchLabels:
          io.kubernetes.pod.namespace: {{ $.Release.Namespace }}
          {{- include "agentEnv.selectorLabels" $ | nindent 10 }}
      {{- if $svc.ports }}
      toPorts:
        - ports:
{{ include "agentEnv.servicePortsListFor" (dict "svc" $svc) | nindent 12 }}
      {{- end }}
  {{- end }}
{{- end }}
