{{- if and .Values.serviceAccountCreate (not .Values.serviceAccountName) }}
{{- fail "serviceAccountName must be set when serviceAccountCreate is true" }}
{{- end }}
{{- if and .Values.serviceAccountCreate .Values.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentEnv.labels" . | nindent 4 }}
{{- end }}
