{{- if .Values.serviceAccount }}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default "task-s3-access" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentEnv.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- range $k, $v := . }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
