services:
  default:
    image: 123456789.dkr.ecr.eu-west-2.amazonaws.com/agent-environment:1.0.0
    workingDir: /root
    dnsRecord: true
    env:
    - name: VICTIM_HOSTNAME
      value: victim
    volumes:
    - shared-volume:/root
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 0.5
        memory: 1Gi
  victim:
    image: 123456789.dkr.ecr.eu-west-2.amazonaws.com/victim:1.0.0
    dnsRecord: true
    readinessProbe:
      exec:
        command:
        - curl
        - -f
        - http://localhost:8080/health
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 3
    resources:
      limits:
        memory: 2Gi
  ghidra:
    image: 123456789.dkr.ecr.eu-west-2.amazonaws.com/ghidra:1.0.0
    dnsRecord: true
    volumes:
    - shared-volume:/root
    resources:
      limits:
        memory: 2Gi
volumes:
  shared-volume: null
