[project]
name = "k8s-docs"
version = "0.1.0"
description = "Docs site for k8s_sandbox"
authors = [{name = "UK AI Security Institute"}]
requires-python = ">=3.10"
dependencies = [
    "mkdocs-material>=9.5.44",
]
