name: Type check using Mypy

on:
  workflow_call:

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade uv
          pip install uv
          uv sync
      - name: Type check with mypy
        run: uv run mypy .
